security:
    # 1. ENCRIPTACIÓN: Definimos que las contraseñas se hashean
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # 2. PROVEEDOR: Le decimos a Symfony que busque usuarios en la Entidad "Usuario" usando el campo "email"
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email

    # 3. FIREWALLS: Las reglas del juego
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Configuración del Formulario de Login
            form_login:
                # Nombre de la ruta del login (que definimos en LoginController)
                login_path: app_login
                check_path: app_login
                # Redirigir al home después de loguearse con éxito
                default_target_path: app_inicio 
                # Permitir que el login funcione
                enable_csrf: true

            # Configuración del Logout
            logout:
                path: app_logout
                # A dónde ir después de salir
                target: app_inicio

    # 4. CONTROL DE ACCESO: Aquí definimos tus reglas de negocio
    access_control:
        # A. Solo el ADMIN puede entrar a rutas que empiecen con /admin (gestionar mascotas, etc)
        - { path: ^/admin, roles: ROLE_ADMIN }

        # B. TU REGLA DE ORO:
        # Cualquier ruta que empiece con /mis-solicitudes requiere estar logueado (ROLE_USER).
        # Si un anónimo entra, Symfony lo manda al Login automáticamente.
        - { path: ^/mis-solicitudes, roles: ROLE_USER }